# Generated by Django 4.0.2 on 2022-04-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_profile_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social/static/social/posts/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='social/static/social/avatars/'),
        ),
    ]
