# Generated by Django 4.0.2 on 2022-06-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
