# Generated by Django 4.0.2 on 2022-06-03 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_rename_coin_profile_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coins',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_coins', to='social.profile'),
        ),
    ]
